[package]
name = "wych_book"
version = "0.0.0"
edition = "2021"


[dependencies]
csv = "1.2.2"
rand = "0.8.5"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
home = "0.5.5"


[dev-dependencies]
tempdir = "0.3.7"